name: Homeplex
description: complete home solution

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  esewa_flutter_sdk:
    path: esewa_flutter_sdk
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.11
  rating_dialog: ^2.0.3
  provider: ^6.0.2
  image_picker: ^0.8.5
  nepali_date_picker: ^5.3.0
  fluttertoast: ^8.0.8
  google_fonts: ^3.0.1
  url_launcher: ^6.0.9
  carousel_slider: ^4.1.1
  eva_icons_flutter: ^3.1.0
  dots_indicator: ^2.0.0
  align_positioned: ^3.0.0
  permission_handler: ^9.2.0
  flutter_spinkit: ^5.1.0
  maps_launcher: ^2.0.1
  flutter_markdown: ^0.6.10+3
  geocoding: ^2.0.4
  location: ^4.3.0
  open_app_settings: ^2.0.1
  uuid:
  google_maps_flutter: ^2.1.3
  webview_flutter: ^2.0.4
  get: ^4.1.4
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  firebase_crashlytics: ^2.8.9
  firebase_analytics: ^9.3.3
  multi_image_picker: ^4.8.1
  font_awesome_flutter: ^10.2.1
  clipboard: ^0.1.3
  image_gallery_saver: ^1.7.1
  dio: ^4.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/esewa/
